In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [4]:
data_1d = np.array([1,2,3,4,5])

In [6]:
data_2d = np.array([[1,2,3],[1,2,3]])

In [7]:
print(data_1d.shape)

(5,)


In [8]:
print(data_2d.shape)

(2, 3)


In [13]:
#array reshaping
reshaped_Arr = data_2d.reshape(3,2)
reshaped_Arr

array([[1, 2],
       [3, 1],
       [2, 3]])

In [14]:
data_1d

array([1, 2, 3, 4, 5])

In [15]:
print(data_1d[0])

1


In [16]:
print(data_2d[1,2])

3


In [18]:
print(data_1d[:3])

[1 2 3]


In [19]:
data_2d

array([[1, 2, 3],
       [1, 2, 3]])

In [20]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [21]:
addition = a+b

In [22]:
addition

array([5, 7, 9])

In [23]:
exp_a=np.exp(a)

In [24]:
a=np.array([1,2,3])
b=10

result = a+b
result


12